version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: app_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: app_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"


  postgres:
    image: postgres:latest
    container_name: app_my_postgres_db
    restart: always
    environment:
      POSTGRES_DB: dev-customer-point
      POSTGRES_USER: username1
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: app_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  
  