spring:
  application:
    name: customer-point-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/dev-customer-point}
    username: ${DATASOURCE_USERNAME:thong}
    password: ${DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:http://localhost:9092}
    consumer:
      group-id: group-id-test
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

service:
  kafka:
    modify-point-topic: com.thong1.modify-point-topic